numero = int(input('Seu numero: '))
i = 0
print('{} X {} = {}'.format(numero, i, numero * i))
i = i + 1
print('{} X {} = {}'.format(numero, i, numero * i))
i = i + 1
print('{} X {} = {}'.format(numero, i, numero * i))
i = i + 1
print('{} X {} = {}'.format(numero, i, numero * i))
i = i + 1
print('{} X {} = {}'.format(numero, i, numero * i))
i = i + 1
print('{} X {} = {}'.format(numero, i, numero * i))
i = i + 1
print('{} X {} = {}'.format(numero, i, numero * i))
i = i + 1
print('{} X {} = {}'.format(numero, i, numero * i))
i = i + 1
print('{} X {} = {}'.format(numero, i, numero * i))
i = i + 1
print('{} X {} = {}'.format(numero, i, numero * i))
i = i + 1
print('{} X {} = {}'.format(numero, i, numero * i))
i = i + 1

